### ISSUE TITLE
Collisions with DNS

### ISSUE THREAD

**Issue by keithjjones** [cisagov/icsnpp-enip#19]
I have seen collisions with enip on a network I can monitor, but can't share data from.  We had a similar issue with bacnet and DNS and what I did was only search for bacnet via the dpd sig on ports >= 1024.  Maybe something similar should be done here?  At least port 53 should be ignored with these signatures.  

https://github.com/cisagov/icsnpp-enip/blob/64fb2bfe20080cc4e17205167b75f626b30749e2/scripts/icsnpp/enip/dpd.sig#L29

**Comment by WalmartDeli** [comment]
I was unable to reproduce the collision you discussed with DNS traffic. Is there any additional context you could provide on the type of traffic it might be colliding with?

**Comment by keithjjones** [comment]
Not other than it happened on port 53 several times, and what I remember was legit dns traffic when we looked into a couple.  We saw it on a live customer network.

**Comment by Kleinspider** [comment]
Added the same src-port and dst-port conditions that were added to the BACnet parser to dpd.sig. This should resolve the issue as DNS traffic (port 53) will no longer match the signature.
