### ISSUE TITLE
Capture wrong direction of communication

### ISSUE THREAD

**Issue by HiepTon** [cisagov/icsnpp-enip#21]
# 🐛 Summary #

Capture wrong direction of communication

## To reproduce ##
Version of zeek LTS: 5.0.9
Version of enip plugin: 2.12.0

Just run the pcap file in attachment
## Expected behavior ##

The broadcast messages should be from 192.168.1.105 not from 255.255.255.255

## Any helpful log output or screenshots ##
[conn.log](https://github.com/cisagov/icsnpp-enip/files/12273827/conn.log)
[enip.log](https://github.com/cisagov/icsnpp-enip/files/12273828/enip.log)

See conn.log and enip.log files in attachment
[enip_Issue.zip](https://github.com/cisagov/icsnpp-enip/files/12273841/enip_Issue.zip)

**Comment by Kleinspider** [comment]
I believe this is similar to the issue described in Issue https://github.com/cisagov/icsnpp-enip/issues/11 and has been addressed as of icsnpp-enip version 1.3 and commit https://github.com/cisagov/icsnpp-enip/commit/658380121685e609df9c354ef88907e187b1bfe3. Additional information on the added fields can be found at https://github.com/cisagov/icsnpp-enip#source-and-destination-fields

The enip.log file that gets produced with the newest version of the parser:
[enip.log](https://github.com/cisagov/icsnpp-enip/files/12353260/enip.log)

The fields source_h, source_p, destination_h, and destination_p fields should all contain the correct IP addresses/ports.
