### ISSUE TITLE
Plugin is not working with current master branch of zeek 

### ISSUE THREAD

**Issue by ckmk14** [cisagov/icsnpp-enip#5]
# 🐛 Summary #

After installing the plugin I get the following error message:
![enip](https://user-images.githubusercontent.com/40267060/171021878-80d5537c-a235-4070-9f05-7da230d7bcdc.PNG)

## Any helpful log output or screenshots ##

After changing line 1734 in consts.zeek to

`const cip_device_types = {`

it works.

**Comment by Kleinspider** [comment]
This appears to have been fixed with commit 57b0395d37f8c5318310afedd2ff9205a5cbf809. Thanks!
